name: Derek Bolingbroke
favicon: null
layout_spectrum: 0.6620918051339686
typography_spectrum: 0.6245538841467351
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.038740463089197874
  lightness: 0.34112760052084923
  saturation: 0.07719217985868454
  rhythmicContrast: 0.4799991229083389
purpose: []
