name: Derek Bolingbroke
favicon: null
layout_spectrum: 0.56366
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#f6c6c0'
    - '#e69e95'
    - '#a4496a'
    - '#38180b'
  brandStrength: 0.5
  lightness: 0.4375
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
